#####
# Hostname:
#####
hostname_server: sauron


#####
# Config System Users:
#####
www_users:
  - admin


#####
# SSH RSA:
#####
ssh_key_path: /ansible/conf/private/ssh/aws_id_rsa


#####
# List of apt packages to install:
#####
list_additional_pkg:
  - git-all
  - nginx
  - python3-venv


#####
# Vhosts:
#####
# Paths ansible conf:
src_vhosts_path: /ansible/conf/sauron/vhosts

symbolic_link_vhost:
  - ci_helmcode_com.conf
